name: Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Update F-Droid build string
      run: |
        git config --global user.email "cli@github.com"
        git config --global user.name "Github Actions"

        git clone --depth=1 --branch=master https://github.com/RlCCJ/MindustryBuilds
        cd MindustryBuilds
        echo "Updating version to ${RELEASE_VERSION:1}"
        BNUM=$(($GITHUB_RUN_NUMBER + 1000))
        echo versionName=CN-ARC-v7-${RELEASE_VERSION:1}$'\n'versionCode=${BNUM} > version_fdroid.txt
        git add .
        git commit -m "Updating to build ${RELEASE_VERSION:1}"
        git push https://RlCCJ:${{ secrets.API_TOKEN_GITHUB }}@github.com/RlCCJ/MindustryBuilds

    - uses: actions/checkout@v2
    - name: Set env-LC test
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Update F-Droid build string
      run: |
        git clone --depth=1 --branch=master https://github.com/xkldklp/Mindustry-CN-ARC-Builds
        cd Mindustry-CN-ARC-Builds
        echo "Updating version to ${RELEASE_VERSION:1}"
        BNUM=$(($GITHUB_RUN_NUMBER + 1000))
        echo versionName=CN-ARC-v7-${RELEASE_VERSION:1}$'\n'versionCode=${BNUM} > version_fdroid.txt
        git add .
        git commit -m "Updating to build ${RELEASE_VERSION:1}"
        git push https://xkldklp:${{ secrets.API_TOKEN_GITHUB }}@github.com/xkldklp/Mindustry-CN-ARC-Builds